package hr.fer.zemris.java.hw04.lexer;

/**
 * Token types that are generated by {@link QueryLexer}.
 * 
 * @author Mihael Jaić
 *
 */

public enum QueryTokenType {
	/**
	 * Attribute
	 */
	ATTRIBUTE,
	/**
	 * Operator.
	 */
	OPERATOR,
	/**
	 * String literal.
	 */
	STRING_LITERAL,
	/**
	 * And operator.
	 */
	AND,
	/**
	 * End of file.
	 */
	EOF
}
