package hr.fer.zemris.java.hw04.lexer;

/**
 * Tokens that are generated by {@link QueryLexer}. Token types are defined in {@link QueryTokenType}.
 * 
 * @author Mihael Jaić
 *
 */

public class QueryToken {
	/**
	 * Type of token.
	 */
	private QueryTokenType type;
	/**
	 * Value of token.
	 */
	private String value;
	
	/**
	 * Sets token's value and type.
	 * 
	 * @param type	Type
	 * @param value	Value.
	 */
	
	public QueryToken(QueryTokenType type, String value) {
		super();
		this.type = type;
		this.value = value;
	}
	
	/**
	 * Gets token type.
	 * 
	 * @return Token type.
	 */
	
	public QueryTokenType getType() {
		return type;
	}
	
	/**
	 * Gets token value.
	 * 
	 * @return	Token value.
	 */
	
	public String getValue() {
		return value;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		QueryToken other = (QueryToken) obj;
		if (type != other.type)
			return false;
		if (value == null) {
			if (other.value != null)
				return false;
		} else if (!value.equals(other.value))
			return false;
		return true;
	}
	
	
}
