package hr.fer.zemris.java.hw03.prob1;

/**
 * Token is symbol generated by lexer which has its value and type. Type of
 * token describes how lexer interpreted part of input string see
 * {@link TokenType}.
 * 
 * @author Mihael Jaić
 *
 */

public class Token {
	/**
	 * Type of token.
	 */
	private TokenType type;
	/**
	 * Value of token.
	 */
	private Object value;

	/**
	 * Constructor which sets type and value of token.
	 * 
	 * @param type
	 *            Type of token.
	 * @param value
	 *            Value of token.
	 */

	public Token(TokenType type, Object value) {
		this.type = type;
		this.value = value;
	}

	/**
	 * Gets value of token.
	 * 
	 * @return Value of token.
	 */

	public Object getValue() {
		return value;
	}

	/**
	 * Gets type of token.
	 * 
	 * @return Type of token.
	 */

	public TokenType getType() {
		return type;
	}
}
