package hr.fer.zemris.java.hw03.prob1;

/**
 * Types of token generated by lexer.
 * 
 * @author Mihael Jaić
 *
 */

public enum TokenType {
	/**
	 * End of file.
	 */
	EOF,
	/**
	 * String that has only letters in it.
	 */
	WORD,
	/**
	 * Number.
	 */
	NUMBER,
	/**
	 * Character that isn't letter, digit or space.
	 */
	SYMBOL;
}
